### PR TITLE
Standardization update

### PR DESCRIPTION
**Pull request by ObserverOfTime**
This PR updates the repository to use the new bindings and standard workflows.

I need you to do two things for automated package publishing, if you don't mind:

1. Deprecate your node package (will be published in the org scope):

```bash
npm deprecate "@muniftanjim/tree-sitter-lua@*" "Replaced with @tree-sitter-grammars/tree-sitter-lua" 
```

2. Add the org team as an owner to the rust package:

```bash
cargo owner --add "github:tree-sitter-grammars:crates"
```

### CODE REVIEW

**Comment by clason** [comment]
@MunifTanjim

**Comment by MunifTanjim** [comment]
Got this:

```
❯ cargo owner --add "github:tree-sitter-grammars:crates"
    Updating crates.io index
error: failed to invite owners to crate `tree-sitter-lua` on registry at https://crates.io

Caused by:
  the remote server responded with an error (status 400 Bad Request): could not find the github team tree-sitter-grammars/crates
```

@ObserverOfTime

**Review by MunifTanjim — APPROVED** [review]

**Comment by ObserverOfTime** [comment]
I think that's rust-lang/cargo#11505.
See if the proposed solution works.

**Comment by MunifTanjim** [comment]
Not sure how to follow that. Don't think I have permissions to do those for this org.

**Comment by ObserverOfTime** [comment]
It's already set up for the org. You should set it up on your own account.

**Comment by MunifTanjim** [comment]
It still doesn't work. Getting the same error.

I've removed `crates.io` from my github account and connected again (as suggested in that issue). Not sure how that would help in this situation tho. I can't see any teams under https://github.com/tree-sitter-grammars org.

**Comment by clason** [comment]
@MunifTanjim I set it to "visible" -- can you try again? (Sorry about the mess.)

**Comment by ObserverOfTime** [comment]
Does it work now that it's visible? If not, add me as an owner and I'll handle it. (You can remove me afterwards.)

**Comment by MunifTanjim** [comment]
Still doesn't work. What's your username for crates.io?

**Comment by MunifTanjim** [comment]
> I set it to "visible"

image

I still can't see the "Teams" tab on https://github.com/orgs/tree-sitter-grammars. 

It would look like this when I have access to see teams:

image

**Comment by clason** [comment]
Guess you need to be an organization member then. Sorry!

**Comment by ObserverOfTime** [comment]
> Still doesn't work. What's your username for crates.io?

It's the same as here. That's how crates works.

**Comment by clason** [comment]
I added you to the team (and org).

**Comment by ObserverOfTime** [comment]
That's another solution.

**Comment by MunifTanjim** [comment]
It worked 🙌🏼

**Comment by MunifTanjim** [comment]
I'll deprecate the npm package once the new package is published.

**Comment by ObserverOfTime** [comment]
Time to merge, tag, and pray.

**Comment by ObserverOfTime** [comment]
The packages have been published.

**Pull request merged**
